//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "form_answer")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub form_id: i32,
    pub answerer_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::form::Entity",
        from = "Column::FormId",
        to = "super::form::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Form,
    #[sea_orm(has_many = "super::question_answer::Entity")]
    QuestionAnswer,
}

impl Related<super::form::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Form.def()
    }
}

impl Related<super::question_answer::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::QuestionAnswer.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
