//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub mod prelude;

pub mod form;
pub mod form_answer;
pub mod post;
pub mod post_tag;
pub mod post_volunteer;
pub mod question;
pub mod question_answer;
pub mod review;
pub mod tag;
pub mod user;
pub mod user_recruit;
pub mod user_tag;
