//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "question_answer")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub form_answer_id: i32,
    pub question_id: i32,
    #[sea_orm(column_type = "Text")]
    pub answer: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::form_answer::Entity",
        from = "Column::FormAnswerId",
        to = "super::form_answer::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    FormAnswer,
}

impl Related<super::form_answer::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FormAnswer.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
