//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "user")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub student_id: i32,
    #[sea_orm(column_type = "Text")]
    pub self_introduction: String,
    #[sea_orm(unique)]
    pub email: String,
    pub password: String,
    pub created_at: DateTime,
    pub portfolio_path: String,
    pub profile_path: String,
    #[sea_orm(column_type = "Double")]
    pub rating: f64,
    pub is_active: bool,
    pub is_admin: bool,
    pub is_will_deleted: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::post::Entity")]
    Post,
    #[sea_orm(has_many = "super::user_tag::Entity")]
    UserTag,
}

impl Related<super::post::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Post.def()
    }
}

impl Related<super::user_tag::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserTag.def()
    }
}

impl Related<super::tag::Entity> for Entity {
    fn to() -> RelationDef {
        super::user_tag::Relation::Tag.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::user_tag::Relation::User.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
